# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c06e6db2c8807f1f43ebc57ac2e2e2b61174d8cd8e65fe9fc0e988c32257c05793528cdb8de1bd9f01fffc769c294428676cd5b66f6331f3b141dcbe55ff57

test:
  secret_key_base: 73f9353d0993ef303f3976a5c6770a1084d75cba1d359f5b202a49a1ba1910f8238eda983e716df6c008714a93fbc12bdb386857b5704e504f4eeb9ae36ee3b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
